[package]
name = "jam-audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jam-core.workspace = true
jam-dsp.workspace = true
cpal.workspace = true
rtrb.workspace = true
hound.workspace = true
symphonia.workspace = true
rubato.workspace = true
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
