[package]
name = "jam-band"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
jam-core.workspace = true
jam-dsp.workspace = true
jam-audio.workspace = true
rustysynth.workspace = true
rand.workspace = true
rand_pcg.workspace = true
thiserror.workspace = true
